"""empty message

Revision ID: 55ebe5e5f041
Revises: d3f5afd8fabb
Create Date: 2024-06-19 12:25:05.433186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ebe5e5f041'
down_revision = 'd3f5afd8fabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('last_attempt',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_attempt',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
